// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package grpcserver

import (
	"context"
	"github.com/Goboolean/command-server/internal/adapter/grpc"
)

// Injectors from wire.go:

func InitializeHost(ctx context.Context) (*Host, error) {
	metadataCommandAdapter := grpcadapter.New()
	host := New(metadataCommandAdapter)
	return host, nil
}
