// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package grpcserver

import (
	"context"
	"github.com/Goboolean/command-server/internal/adapter/grpc/metadata"
	grpcadapter2 "github.com/Goboolean/command-server/internal/adapter/grpc/model"
	grpcadapter3 "github.com/Goboolean/command-server/internal/adapter/grpc/user"
)

// Injectors from wire.go:

func InitializeHost(ctx context.Context) (*Host, error) {
	metadataAdapter := grpcadapter.New()
	modelAdapter := grpcadapter2.New()
	userAdapter := grpcadapter3.New()
	host := New(metadataAdapter, modelAdapter, userAdapter)
	return host, nil
}
